//created on: Aug 5, 2021
package model

//list any import classes here.

import model.*;

//declare any global variables here




rule "Next Step"
    when
        $f : FacilityAgent( demo_step != 0 )
        $m : ManagerAgent()
        $e : EligibilityAgent()
        $p : ProviderAgent()
        $s : ServiceAgent()
        $l : LevelOfCareAgent()
        $n : MedNecAgent()
    then
        $m.nextStep();
        $e.nextStep();
        $p.nextStep();
        $s.nextStep();
        $l.nextStep();
        $n.nextStep();
end

rule "Reset" salience 1
    when
        $f : FacilityAgent( demo_step == 0 )
        $m : ManagerAgent()
        $e : EligibilityAgent()
        $p : ProviderAgent()
        $s : ServiceAgent()
        $l : LevelOfCareAgent()
        $n : MedNecAgent()
    then
    	//System.out.println("RESET");
    	$f.setDemo_step(0);
        $m.setDemo_step(0);
        $e.setDemo_step(0);
        $p.setDemo_step(0);
        $s.setDemo_step(0);
        $l.setDemo_step(0);
        $n.setDemo_step(0);
end

